CI for checking C Build
courselab/snaskii22 pull request #44
Opened 2022-11-30 05:36 UTC by gp2112

2022-11-30 12:10 UTC, monacofj commented on .github/workflows/c-cpp.yml
> +name: C/C++ CI
What issue this PR refers to?

2022-11-30 23:11 UTC, CerqueiraMatheus requested changes
According to [CONTRIBUTING.md](https://github.com/courselab/snaskii22/blob/main/doc/CONTRIBUTING.md), you should first open an issue describing the problem and then open a pull request fixing it. I think that as you already opened this PR it would be ok if you create an issue and link this.

2022-12-02 15:17 UTC, gp2112 commented on .github/workflows/c-cpp.yml
> +name: C/C++ CI
I've just created one, sorry
#61

2022-12-02 17:56 UTC, Math-42 approved these changes

2022-12-02 23:08 UTC, CerqueiraMatheus approved these changes

2022-12-02 23:09 UTC, merged