Added PT-BR version to readme file
courselab/snaskii22 pull request #79
Opened 2022-12-06 15:15 UTC by mafemello

2022-12-10 18:33 UTC, PauloMRocha requested changes

2022-12-10 18:33 UTC, PauloMRocha commented on README.md
> +Por outro lado, se você obteu o software de __distribution repository__, geralmente como tarball,
I think that "se você obteve" would be better here

2022-12-10 18:33 UTC, PauloMRocha commented on README.md
> +Tenha cuidado, no entanto. As bordas da arena são eletrificadas e matariam a cobrinha se forem tocadas. Além disso, lembre-se que a cobra é venenosa e também morreria se
The verbal time is wrong here.
I sugest to use the sentences : "As bordas da arena são eletrificadas e matariam a cobrinha se fossem tocadas" and "Além disso, lembre-se que a cobra é venenosa e também morreria caso se mordesse acidentalmente".

2022-12-10 18:33 UTC, PauloMRocha commented on README.md
> +Snaskii é um jogo de cobra ASCII muito simples, uma homenagem ao clássico
I think that "jogo da cobrinha" is a more common name in Brazil, but "jogo de cobrea" is ok too.

2022-12-14 13:58 UTC, SusyDutra commented
Changed the suggestions @PauloMRocha made

2022-12-15 02:03 UTC, joaomisson approved these changes
LGTM

2022-12-17 18:02 UTC, closed without merging